---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: enceladus
description: My personal flavor of Fedora Silverblue.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      # - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
      - https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
    keys:
      # - https://repo.vivaldi.com/archive/linux_signing_key.pub
      - https://pkg.cloudflareclient.com/pubkey.gpg
    optfix:
      - google/chrome
    install:
      # - vivaldi-stable
      - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - cloudflare-warp
      - fish
      - gnome-backgrounds-extras
      - sushi
    remove:
      - fedora-workstation-backgrounds
      - desktop-backgrounds-gnome
      - f42-backgrounds-gnome
      - firefox
      - firefox-langpacks
      # Remove GNOME Classic session
      - gnome-classic-session
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      # Remove some stuff from ublue-os/main
      - adw-gtk3-theme
      - distrobox
      - gnome-tweaks
      - htop
      - nvtop

  - type: default-flatpaks
    notify: true
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        # Default GNOME apps
        - org.gnome.baobab
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Decibels # incubator app
        - org.gnome.Epiphany
        - org.gnome.Extensions
        - org.gnome.Showtime # incubator app
        - org.gnome.Snapshot
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.Extensions
        - org.gnome.font-viewer
        - org.gnome.TextEditor
        - org.gnome.Loupe
        - org.gnome.Logs
        - org.gnome.Maps
        - org.gnome.Music
        - org.gnome.Papers # incubator app
        - org.gnome.Weather
        # Extra
        - com.mattjakeman.ExtensionManager
      remove:
        - org.gnome.Evince
        - org.gnome.NautilusPreviewer

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
